// Self-contained demo: no fonts, scripts, images or analytics fetched elsewhere.
export function tourWebsitePage(marker: string) {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="opendock-demo" content="${marker}">
<meta name="description" content="A little website. A big first step. Built in a container with Yougori.">
<title>Hello World! · Made with Yougori</title>
<style>
:root{color-scheme:light;--paper:#f5f2ec;--ink:#191c21;--muted:#656a70;--line:#dcdad4;--blue:#2f5eaa;--green:#357657}
*{box-sizing:border-box}html{scroll-behavior:smooth;scroll-padding-top:24px}body{margin:0;background:var(--paper);color:var(--ink);font-family:Inter,"Segoe UI",Arial,sans-serif;-webkit-font-smoothing:antialiased}a{color:inherit}a:focus-visible{outline:3px solid var(--blue);outline-offset:5px}::selection{background:#c9dafa}svg{display:block}nav,main,footer{width:min(1120px,calc(100% - 64px));margin:auto}
.nav{min-height:100px;display:flex;align-items:center;justify-content:space-between;gap:20px;border-bottom:1px solid var(--line)}.brand{display:flex;align-items:center;gap:10px;text-decoration:none;font-size:21px;font-weight:700;letter-spacing:-.8px}.brand svg{width:29px;height:29px}.nav-note{font-size:11px;letter-spacing:1.8px;text-transform:uppercase;color:var(--muted)}.live{display:inline-flex;align-items:center;gap:8px;font-size:12px;font-weight:600}.dot{width:7px;height:7px;flex-shrink:0;border-radius:50%;background:#65ac83;box-shadow:0 0 0 4px #65ac8316}
.hero{display:grid;grid-template-columns:1.15fr 1fr;gap:64px;align-items:center;padding:88px 0 76px}.eyebrow{display:flex;align-items:center;gap:12px;margin:0 0 27px;font-size:11px;text-transform:uppercase;letter-spacing:2.2px;font-weight:650}.eyebrow:before{content:"";height:1px;width:30px;background:var(--blue)}h1{font-size:clamp(64px,7.4vw,100px);line-height:.99;font-weight:550;letter-spacing:-7px;margin:0 0 28px;max-width:550px}h1 span{color:var(--blue)}.intro{max-width:380px;font-size:17px;line-height:1.8;color:var(--muted);margin:0}.actions{display:flex;align-items:center;gap:24px;flex-wrap:wrap;margin-top:32px}.button{display:inline-flex;align-items:center;justify-content:space-between;gap:30px;padding:16px 20px;border-radius:6px;background:var(--ink);color:white;text-decoration:none;font-size:13px;font-weight:600;transition:background .2s,transform .2s}.button:hover{background:var(--blue);transform:translateY(-2px)}.quiet-link{font-size:12px;text-decoration:underline;text-underline-offset:5px}.caption{display:flex;gap:8px;align-items:center;font-size:11px;color:var(--muted);margin-top:27px}.caption svg{width:14px;height:14px;color:var(--green)}
.visual{position:relative;border:1px solid #303945;border-radius:16px;background:#191e26;color:#eef2f8;overflow:hidden;box-shadow:0 24px 55px -24px #191c2155;transform:rotate(2deg)}.visual-top{display:flex;justify-content:space-between;align-items:center;gap:12px;border-bottom:1px solid #ffffff12;padding:18px 22px;font:10px ui-monospace,Consolas,monospace;color:#9faabe}.window-dots{display:flex;gap:5px}.window-dots i{width:5px;height:5px;border-radius:50%;background:#667180}.art{height:265px;position:relative;display:grid;place-items:center;background-image:radial-gradient(#9eafd327 .8px,transparent .8px);background-size:20px 20px}.art:before,.art:after{content:"";position:absolute;width:225px;height:225px;border:1px solid #9eafd31a;border-radius:50%}.art:after{width:170px;height:170px}.cube{position:relative;width:154px;height:174px;filter:drop-shadow(0 18px 22px #080d1e88);animation:float 6s ease-in-out infinite}.orbit-label{position:absolute;font:10px ui-monospace,Consolas,monospace;color:#a4b7d5;padding:6px 9px;border:1px solid #ffffff15;border-radius:5px;background:#1e2530}.orbit-label.one{top:36px;left:24px}.orbit-label.two{bottom:26px;right:24px}.visual-bottom{margin:0 18px 18px;padding:19px 20px;border:1px solid #ffffff12;border-radius:9px;background:#ffffff04}.code-comment{font:10px ui-monospace,Consolas,monospace;color:#8898b0;margin:0 0 12px}.code-line{font:13px/1.6 ui-monospace,Consolas,monospace;color:#c4d4ef}.code-line span{color:#90cba7}.visual-status{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:17px;padding-top:15px;border-top:1px solid #ffffff12;font-size:10px;color:#9eaec7}.visual-status .live{font-size:10px;color:#b6ddc5}.visual-status .dot{width:5px;height:5px}
.milestone{display:flex;justify-content:space-between;align-items:center;gap:30px;padding:26px 0;border-top:1px solid var(--line);border-bottom:1px solid var(--line)}.milestone p{margin:0;font-size:13px;line-height:1.7}.milestone p span{color:var(--muted)}.milestone-label{font-size:10px;letter-spacing:1.6px;text-transform:uppercase;color:var(--green);white-space:nowrap}.section{padding:65px 0}.section-heading{display:flex;align-items:baseline;justify-content:space-between;gap:20px;margin-bottom:30px}h2{font-size:29px;letter-spacing:-1px;font-weight:550;margin:0}.section-heading p{font-size:12px;color:var(--muted);margin:0}.steps{display:grid;grid-template-columns:repeat(3,1fr);gap:36px}.step{border-top:1px solid var(--line);padding-top:20px}.step-number{font:11px ui-monospace,Consolas,monospace;color:var(--blue)}h3{font-size:16px;letter-spacing:-.3px;margin:17px 0 9px;font-weight:600}.step p{font-size:13px;line-height:1.85;color:var(--muted);margin:0}.next{display:flex;align-items:center;justify-content:space-between;gap:30px;padding:35px 38px;margin:0 0 60px;border:1px solid #ced8e6;border-radius:10px;background:#e9edf3}.next h2{font-size:23px}.next p{font-size:13px;line-height:1.8;color:var(--muted);margin:9px 0 0}.next-mark{font-size:36px;color:var(--blue)}footer{display:flex;justify-content:space-between;gap:20px;padding:25px 0 32px;border-top:1px solid var(--line);font-size:11px;color:var(--muted)}footer strong{font-weight:600;color:var(--ink)}
@keyframes float{50%{transform:translateY(-9px)}}@media(min-width:1400px){.hero{padding-top:100px;padding-bottom:90px}}@media(max-width:850px){.hero{gap:30px}h1{letter-spacing:-4px}.nav-note{display:none}.steps{gap:22px}.visual{transform:none}}@media(max-width:640px){nav,main,footer{width:calc(100% - 40px)}.nav{min-height:78px}.hero{grid-template-columns:1fr;padding:50px 0 38px;gap:38px}h1{font-size:76px;letter-spacing:-5px}.intro{font-size:16px}.visual{width:100%;max-width:420px;justify-self:center}.art{height:230px}.milestone{align-items:flex-start;flex-direction:column;gap:10px}.section{padding:42px 0}.section-heading{display:block}.section-heading p{margin-top:12px}.steps{grid-template-columns:1fr;gap:26px}.step h3{margin-top:12px}.next{padding:25px;margin-bottom:40px}.next h2{font-size:21px}footer{line-height:1.6;font-size:10px}.actions{gap:20px}.eyebrow{margin-bottom:24px}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}.cube{animation:none}.button{transition:none}}
</style>
</head>
<body>
<nav class="nav" aria-label="Main navigation"><a class="brand" href="#" aria-label="Yougori home"><svg viewBox="0 0 32 32" fill="none" aria-hidden="true"><path d="m16 2 13 7.5v13L16 30 3 22.5v-13L16 2Z" stroke="currentColor" stroke-width="1.7"/><path d="m3 9.5 13 8 13-8M16 17.5V30M9.5 5.7l13 7.8" stroke="currentColor" stroke-width="1.7"/></svg>Yougori</a><span class="nav-note">Your first creation</span><span class="live"><span class="dot"></span>Website is running</span></nav>
<main>
<section class="hero" aria-labelledby="hello"><div><p class="eyebrow">A little website. A big first step.</p><h1 id="hello">Hello<br><span>World!</span></h1><p class="intro">An idea, a container, and you're off.<br>Your first website is up and running. Imagine what you'll build next.</p><div class="actions"><a class="button" href="#how-it-works">See how it works <span aria-hidden="true">↗</span></a><a class="quiet-link" href="#next">What's next?</a></div><p class="caption"><svg viewBox="0 0 16 16" fill="none" aria-hidden="true"><circle cx="8" cy="8" r="6.5" stroke="currentColor"/><path d="m4.5 8 2.2 2.2 4.8-4.8" stroke="currentColor" stroke-width="1.5"/></svg>Made in your container. Powered by your curiosity.</p></div>
<div class="visual" role="img" aria-label="A blue container cube above a running Hello World website"><div class="visual-top"><span class="window-dots"><i></i><i></i><i></i></span><span>my-first-website</span><span>↗</span></div><div class="art"><span class="orbit-label one">one container</span><svg class="cube" viewBox="0 0 160 180" fill="none" aria-hidden="true"><path d="m80 12 65 37v78l-65 39-65-39V49L80 12Z" fill="#91b4ed"/><path d="m80 88 65-39v78l-65 39V88Z" fill="#416caa"/><path d="m15 49 65 39v78l-65-39V49Z" fill="#608cca"/><path d="m80 12 65 37-65 39-65-39L80 12Z" fill="#adc9f5"/><path d="m47 31 65 38v27l-17 10V79L30 42" fill="#c8dcf9" opacity=".7"/><path d="m15 49 65 39 65-39M80 88v78" stroke="#d8e6ff" stroke-opacity=".45"/><path d="m32 112 23 14v9l-23-14v-9Z" fill="#d8e6ff" opacity=".7"/></svg><span class="orbit-label two">endless possibilities</span></div><div class="visual-bottom"><p class="code-comment">// your first creation</p><div class="code-line">&lt;h1&gt;<span>Hello World!</span>&lt;/h1&gt;</div><div class="visual-status"><span class="live"><span class="dot"></span>Ready to explore</span><span>PORT 3000</span></div></div></div></section>
<div class="milestone"><p><strong>From an empty workspace to something real.</strong><br><span>You just took the first step. This page is the proof.</span></p><span class="milestone-label">✓ First website complete</span></div>
<section class="section" id="how-it-works" aria-labelledby="how-title"><div class="section-heading"><h2 id="how-title">Small steps. Real possibilities.</h2><p>A space to learn, build, and make it yours.</p></div><div class="steps"><article class="step"><span class="step-number">01 / YOUR SPACE</span><h3>A fresh place to build</h3><p>Your container gives your ideas their own Linux workspace, with files and tools together in one place.</p></article><article class="step"><span class="step-number">02 / YOUR CREATION</span><h3>Something you can see</h3><p>Yougori set up this website for you. No copying, no pasting. Just a working starting point for your next idea.</p></article><article class="step"><span class="step-number">03 / YOUR NEXT STEP</span><h3>Share the possibility</h3><p>Back in Yougori, connect port 3000 to Public access to give this page a link you can share.</p></article></div></section>
<section class="next" id="next" aria-labelledby="next-title"><div><h2 id="next-title">Every great project starts somewhere.</h2><p>A portfolio. A tiny app. An experiment just for you.<br>Return to Yougori, finish the guide, and make your next move.</p></div><span class="next-mark" aria-hidden="true">↗</span></section>
</main>
<footer><span>Built with <strong>Yougori</strong></span><span>Your machine. Your workspace. Your ideas.</span></footer>
</body></html>`
}
