import { test, expect } from "@playwright/test"

test("host terminal setup, real xterm input, tabs, hide, close, and compact responsive layout", async ({ page, context }) => {
  test.setTimeout(60000)
  await context.grantPermissions(["clipboard-read", "clipboard-write"])
  const errors: string[] = []
  const pending = new Set<string>()
  page.on("request", request => pending.add(request.url()))
  page.on("requestfinished", request => pending.delete(request.url()))
  page.on("pageerror", error => { errors.push(error.message); console.error(error.stack) })
  await page.goto("/")
  await page.getByRole("button", { name: "Toggle CLI" }).click()
  const dock = page.getByRole("region", { name: "Host terminal", exact: true })
  await expect(dock).toBeVisible({ timeout: 30000 }).catch(error => { console.error("Pending module requests", [...pending]); throw error })
  await expect(dock.getByRole("tab", { name: "PowerShell 1" })).toBeVisible()
  await expect(dock.locator(".host-terminal-working-directory")).toHaveAttribute("title", "C:\\Users\\Test\\Yougori\\Workspace")
  await expect(dock.locator(".host-terminal-starting")).toHaveCount(0)
  await expect(dock.locator(".host-terminal-shell-error")).toHaveCount(0)
  await dock.getByRole("button", { name: "Set up AI agent access" }).click()
  await expect(dock.getByText("AI access ready", { exact: true })).toBeVisible()
  await dock.getByRole("button", { name: "Copy agent guide" }).click()
  await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toContain("Yougori browser test guide")
  const firstInput = dock.locator(".host-terminal-pane:not([hidden]) .xterm-helper-textarea")
  await firstInput.focus()
  await page.keyboard.type("yougori-cli help")
  await page.keyboard.press("Enter")
  await expect(dock.locator(".xterm-screen")).toContainText("Test adapter received input")
  await dock.getByRole("button", { name: "Start Codex" }).click()
  await expect(dock.getByRole("tab", { name: "Codex", exact: true })).toHaveAttribute("aria-selected", "true")
  await expect(dock.locator(".host-terminal-pane:not([hidden]) .xterm-screen")).toContainText("Test adapter received input")
  await dock.getByRole("button", { name: "Hide terminal", exact: true }).click()
  await expect(dock).toBeHidden()
  await page.getByRole("button", { name: "Toggle CLI" }).click()
  await expect(dock.getByRole("tab")).toHaveCount(2)
  await dock.getByRole("button", { name: "End Codex" }).click()
  await dock.getByRole("button", { name: "End terminal", exact: true }).click()
  await expect(dock.getByRole("tab")).toHaveCount(1)
  await expect(dock.getByRole("tab", { name: "PowerShell 1" })).toHaveAttribute("aria-selected", "true")
  for (const width of [1280, 980, 520]) {
    await page.setViewportSize({ width, height: 800 })
    const dimensions = await dock.evaluate(element => {
      const terminal = element.querySelector(".host-terminal-content")!.getBoundingClientRect()
      const toolbar = element.querySelector(".host-terminal-toolbar")!.getBoundingClientRect()
      return { width: element.getBoundingClientRect().width, scrollWidth: element.scrollWidth, terminalHeight: terminal.height, toolbarHeight: toolbar.height }
    })
    expect(dimensions.scrollWidth).toBeLessThanOrEqual(width + 1)
    expect(dimensions.width).toBe(width)
    expect(dimensions.terminalHeight).toBeGreaterThan(90)
    expect(dimensions.toolbarHeight).toBeLessThan(62)
    await expect(dock.getByRole("button", { name: "Hide terminal" })).toBeInViewport()
  }
  await page.setViewportSize({ width: 980, height: 800 })
  const resize = dock.getByRole("separator", { name: "Resize host terminal" })
  const before = Number(await resize.getAttribute("aria-valuenow"))
  await resize.focus(); await page.keyboard.press("ArrowUp")
  await expect(resize).toHaveAttribute("aria-valuenow", String(before + 24))
  await dock.getByRole("button", { name: "Maximize terminal" }).click()
  await expect(resize).toHaveAttribute("aria-valuenow", "704")
  await dock.getByRole("button", { name: "Restore terminal size" }).click()
  await expect(resize).toHaveAttribute("aria-valuenow", String(before + 24))
  await dock.locator(".host-terminal-pane:not([hidden]) .xterm-helper-textarea").focus()
  await page.keyboard.press("Control+Backquote")
  await expect(dock).toBeHidden()
  await page.keyboard.press("Control+Backquote")
  await expect(dock).toBeVisible()
  await expect(dock.getByRole("tab")).toHaveCount(1)
  expect(errors).toEqual([])
})
