// @vitest-environment jsdom
import { StrictMode } from "react"
import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react"
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest"
import { hostTerminalApi, type HostTerminalInfo } from "@/api/host-terminal-api"
import { terminalClipboard } from "@/lib/terminal-clipboard"
import HostTerminalDock from "./host-terminal-dock"

vi.mock("@/api/host-terminal-api", () => ({ hostTerminalApi: { info: vi.fn(), setup: vi.fn(), terminal: vi.fn(), chooseFolder: vi.fn() } }))
vi.mock("@/lib/terminal-clipboard", () => ({ terminalClipboard: { writeText: vi.fn() } }))
vi.mock("@/components/host-terminal-canvas", () => ({ HostTerminalCanvas: ({ tab }: { tab: { id: string; command?: string; reconnect?: boolean; cwd: string } }) => <div data-testid="shell" data-command={tab.command ?? ""} data-reconnect={String(Boolean(tab.reconnect))} data-cwd={tab.cwd}>{tab.id}</div> }))
const info: HostTerminalInfo = { shell: "PowerShell", cwd: "C:\\Users\\Test\\Yougori\\Workspace", cliPath: "C:\\Program Files\\Yougori\\cli\\yougori-cli.exe", elevated: false, maxSessions: 4, sessions: [], skill: { state: "missing", path: "C:\\Users\\Test\\.codex\\skills\\yougori", message: "Needs setup" }, agentInstructions: "Exact agent guide and CLI location", agents: [{ id: "codex", name: "Codex", available: true }, { id: "claude", name: "Claude", available: false }] }
const props = () => ({ visible: true, height: 390, onHeightChange: vi.fn(), onHide: vi.fn() })
beforeEach(() => {
  vi.mocked(hostTerminalApi.info).mockResolvedValue(structuredClone(info))
  vi.mocked(hostTerminalApi.terminal).mockResolvedValue({ data: "", offset: 0, done: false, exitCode: null, truncated: false })
  vi.mocked(terminalClipboard.writeText).mockResolvedValue()
})
afterEach(() => { cleanup(); vi.resetAllMocks() })

describe("host terminal dock", () => {
  it("creates one initial tab under StrictMode, keeps it when hidden, and labels host access", async () => {
    const settings = props()
    const view = render(<StrictMode><HostTerminalDock {...settings} /></StrictMode>)
    await screen.findByRole("tab", { name: "PowerShell 1" })
    expect(screen.getAllByTestId("shell")).toHaveLength(1)
    expect(screen.getByTestId("shell").getAttribute("data-cwd")).toBe(info.cwd)
    expect(screen.getByText("Your computer · Not isolated")).toBeTruthy()
    view.rerender(<StrictMode><HostTerminalDock {...settings} visible={false} /></StrictMode>)
    expect(screen.getAllByTestId("shell")).toHaveLength(1)
    expect(hostTerminalApi.terminal).not.toHaveBeenCalled()
  })
  it("sets up in one click, shows busy state and copies the complete guide", async () => {
    let finish!: (value: HostTerminalInfo["skill"]) => void
    vi.mocked(hostTerminalApi.setup).mockReturnValue(new Promise(resolve => { finish = resolve }))
    render(<HostTerminalDock {...props()} />)
    fireEvent.click(await screen.findByRole("button", { name: "Set up AI agent access" }))
    expect((screen.getByRole("button", { name: "Setting up…" }) as HTMLButtonElement).disabled).toBe(true)
    await act(async () => finish({ ...info.skill, state: "ready", message: "Ready. Open a new Codex session." }))
    expect(screen.getByText("AI access ready")).toBeTruthy()
    expect(hostTerminalApi.setup).toHaveBeenCalledTimes(1)
    fireEvent.click(screen.getByRole("button", { name: "Copy agent guide" }))
    await waitFor(() => expect(terminalClipboard.writeText).toHaveBeenCalledWith(info.agentInstructions))
  })
  it("reports setup failures without pretending success or closing the terminal", async () => {
    vi.mocked(hostTerminalApi.setup).mockRejectedValueOnce(new Error("Personal skill was changed; nothing overwritten"))
    render(<HostTerminalDock {...props()} />)
    fireEvent.click(await screen.findByRole("button", { name: "Set up AI agent access" }))
    expect((await screen.findByRole("alert")).textContent).toContain("nothing overwritten")
    expect(screen.queryByText("AI access ready")).toBeNull()
    expect(screen.getAllByRole("tab")).toHaveLength(1)
  })
  it("only launches detected agents into a fresh tab and enforces the tab limit", async () => {
    render(<HostTerminalDock {...props()} />)
    fireEvent.click(await screen.findByRole("button", { name: "Start Codex" }))
    expect(screen.getAllByTestId("shell").map(shell => shell.getAttribute("data-command"))).toEqual(["", "codex"])
    expect(screen.queryByRole("button", { name: "Start Claude" })).toBeNull()
    fireEvent.click(screen.getByRole("button", { name: "New host terminal" }))
    fireEvent.click(screen.getByRole("button", { name: "New host terminal" }))
    expect(screen.getAllByRole("tab")).toHaveLength(4)
    expect((screen.getByRole("button", { name: "New host terminal" }) as HTMLButtonElement).disabled).toBe(true)
    expect((screen.getByRole("button", { name: "Start Codex" }) as HTMLButtonElement).disabled).toBe(true)
  })
  it("requires confirmation before ending a tab and keeps the other tab", async () => {
    render(<HostTerminalDock {...props()} />)
    await screen.findByRole("tab", { name: "PowerShell 1" })
    fireEvent.click(screen.getByRole("button", { name: "New host terminal" }))
    const id = screen.getAllByTestId("shell")[0]!.textContent
    fireEvent.click(screen.getByRole("button", { name: "End PowerShell 1" }))
    expect(hostTerminalApi.terminal).not.toHaveBeenCalled()
    fireEvent.click(screen.getByRole("button", { name: "Cancel" }))
    expect(screen.queryByRole("alertdialog")).toBeNull()
    fireEvent.click(screen.getByRole("button", { name: "End PowerShell 1" }))
    fireEvent.click(screen.getByRole("button", { name: "End terminal" }))
    await waitFor(() => expect(screen.getAllByRole("tab")).toHaveLength(1))
    expect(hostTerminalApi.terminal).toHaveBeenCalledWith({ sessionId: id, action: "close" })
    expect(screen.getByRole("tab", { name: "PowerShell 2" })).toBeTruthy()
  })
  it("restores existing host shells without launching commands and opens selected folders in new tabs", async () => {
    vi.mocked(hostTerminalApi.info).mockResolvedValueOnce({ ...info, sessions: [{ sessionId: "host-existing", cwd: "C:\\Existing" }] })
    vi.mocked(hostTerminalApi.chooseFolder).mockResolvedValueOnce("C:\\Project with spaces")
    render(<HostTerminalDock {...props()} />)
    expect((await screen.findByTestId("shell")).getAttribute("data-reconnect")).toBe("true")
    fireEvent.click(screen.getByRole("button", { name: "New terminal in a project folder" }))
    await waitFor(() => expect(screen.getAllByTestId("shell")).toHaveLength(2))
    expect(screen.getAllByTestId("shell")[1]!.getAttribute("data-cwd")).toBe("C:\\Project with spaces")
    expect(screen.getAllByTestId("shell")[0]!.getAttribute("data-command")).toBe("")
    fireEvent.click(screen.getByRole("button", { name: "Start Codex" }))
    expect(screen.getAllByTestId("shell")[2]!.getAttribute("data-cwd")).toBe("C:\\Project with spaces")
  })
  it("does not inherit the home folder from an existing tab when starting shells or agents", async () => {
    vi.mocked(hostTerminalApi.info).mockResolvedValueOnce({ ...info, sessions: [{ sessionId: "host-old-home", cwd: "C:\\Users\\Test" }] })
    render(<HostTerminalDock {...props()} />)
    await screen.findByRole("tab", { name: "PowerShell 1" })
    fireEvent.click(screen.getByRole("button", { name: "Start Codex" }))
    fireEvent.click(screen.getByRole("button", { name: "New host terminal" }))
    expect(screen.getAllByTestId("shell").map(shell => shell.getAttribute("data-cwd"))).toEqual(["C:\\Users\\Test", info.cwd, info.cwd])
    expect(hostTerminalApi.terminal).not.toHaveBeenCalled()
  })
  it("supports keyboard resizing, maximizing, and hiding without destructive work", async () => {
    const settings = props()
    render(<HostTerminalDock {...settings} />)
    await screen.findByRole("tab", { name: "PowerShell 1" })
    fireEvent.keyDown(screen.getByRole("separator"), { key: "ArrowUp" })
    expect(settings.onHeightChange).toHaveBeenLastCalledWith(414)
    fireEvent.click(screen.getByRole("button", { name: "Maximize terminal" }))
    expect(settings.onHeightChange).toHaveBeenLastCalledWith(window.innerHeight - 96)
    fireEvent.click(screen.getByRole("button", { name: "Hide terminal" }))
    expect(settings.onHide).toHaveBeenCalledOnce()
    expect(hostTerminalApi.terminal).not.toHaveBeenCalled()
  })
  it("refuses elevated terminals and preserves conflicting custom skills", async () => {
    vi.mocked(hostTerminalApi.info).mockResolvedValueOnce({ ...info, elevated: true, skill: { ...info.skill, state: "conflict", message: "Custom skill left unchanged." } })
    render(<HostTerminalDock {...props()} />)
    await screen.findByText("Custom skill left unchanged.", { exact: false })
    expect(screen.queryAllByRole("tab")).toHaveLength(0)
    expect((screen.getByRole("button", { name: "Set up AI agent access" }) as HTMLButtonElement).disabled).toBe(true)
    expect((screen.getByRole("button", { name: "New host terminal" }) as HTMLButtonElement).disabled).toBe(true)
    expect(hostTerminalApi.setup).not.toHaveBeenCalled()
  })
})
