import type { InstructionsTour, TourStep } from "@/lib/instructions-tour"

export interface TourExplanation { title: string; body: string; hint?: string; target: string; extra?: string[]; interactive?: boolean; next?: string }
export function tourExplanation(step: TourStep, tour: InstructionsTour): TourExplanation {
  const node = tour.environmentId ? `[data-environment-id="${CSS.escape(tour.environmentId)}"]` : "[data-environment-id]"
  const graph = '[data-environment-canvas]'
  const serviceDialog = `[data-service-options="${tour.environmentId ?? ""}"][data-service-port="3000"]`
  const content: Record<TourStep, TourExplanation> = {
    welcome: { title: "Let's look around", body: "First, a tour of the app. Then we'll create a container, give it Internet access, install Codex, open another window and publish a Hello World website with a free public link.", hint: "You decide when to create, run commands or publish. Skip exits the guide, but does not stop programs or disconnect an already published link.", target: '[data-tour="instructions"]' },
    stats: { title: "Your computer, at a glance", body: "These charts show your PC's CPU, GPU and memory usage. Storage is the free space on the drive Yougori uses—not space on every drive combined.", hint: "A virtual disk's capacity is its limit, not necessarily space already used.", target: '[aria-label="Host resources and storage"]' },
    graph: { title: "Your environment map", body: "Every container, GPU container, MicroVM, VM or cloud connection appears as a node here. Drag nodes to arrange them. Use +, − and Fit to navigate.", target: graph },
    "node-controls": { title: "Start, open and stop", body: "A node shows its status and usage. Start opens a local environment; Open returns to a running one. Stop ends its running programs. Closing a window does not stop the environment.", hint: "Cloud nodes use Connect and Disconnect; they do not control the remote server's power.", target: '[data-environment-id]', extra: [] },
    configuration: { title: "Settings and recovery", body: "Click a node's name or Configure to open its sidebar. Change resource limits, save changes, manage connections, take snapshots or back up a stopped environment.", hint: "Factory reset erases environment data. Delete removes the environment. Neither is needed for this tutorial.", target: '[data-tour="node-configure"]' },
    connections: { title: "Connect environments privately", body: "Use a node's left or right connection point—or its connection button—to link two nodes. Choose one-way or both ways, allowed TCP ports, and file/data permissions.", hint: "File access shares a designated connection folder, not the other node's entire disk. Skills explains the saved permissions and offline peers.", target: '[data-tour="node-connect"]' },
    "my-pc": { title: "Share selected PC folders", body: "Connect My PC to a node to choose folders it may access. Nothing is shared just because a node exists. Read-only is the safer starting point.", hint: "Writable shares can change original files on your PC. They are not copies inside the environment.", target: '[data-capability-card="pc"]' },
    "internet-overview": { title: "Wi-Fi or cable: Internet access", body: "This gives an environment Internet access through your PC's existing connection. It works whether your PC uses Wi-Fi or Ethernet; there is no separate Wi-Fi login inside the container.", hint: "Click Internet access, then the connection point at the bottom of a node. You can unplug it again.", target: '[data-capability-card="internet"]' },
    "service-ports": { title: "Add a service port", body: "Click PORT on a container, MicroVM or VM node. In Add a service port, enter the Guest TCP port your app uses, such as 3000, or choose a common port. Click Add port to show it on the node and open its connection options.", hint: "Use 1–65535; 7443 is reserved. Adding a port does not start your app or publish it. Run the app, then connect the port to Local network or Public access separately.", target: '[data-tour="node-port"]' },
    "local-network": { title: "Share a running service locally", body: "A website or database needs a listening port. Its port appears on the node, or you can add one with PORT. Connect that port here to make the service reachable from your PC and permitted private-network devices.", hint: "This is separate from a private node-to-node link. Cloud nodes cannot use this destination.", target: '[data-publication-card="local"]' },
    "public-access": { title: "Publish a service on the web", body: "Connect a local environment's service port to Public access / Cloudflare Tunnel for a public link. Account authentication is optional. Your app still needs its own access protection.", hint: "Later, you can publish our fixed Hello World page. Nothing is published until you press Publish service. Anyone with its link can visit it.", target: '[data-publication-card="public"]' },
    backups: { title: "Bring back a local backup", body: "Load local backup restores a saved Yougori backup as a new environment. To make one, open the node's settings and choose Back up to this PC while it is stopped.", hint: "Keep the whole backup folder together. Shared PC folders and live tunnel connections are not part of that backup.", target: '[data-tour="load-backup"]' },
    "host-terminal": { title: "The terminal on your PC", body: "This opens the host PowerShell or shell, with Yougori CLI and agent-access setup. An AI agent can use the installed Skills to manage environments.", hint: "This is on your real PC, not an isolated container. The walkthrough will use a container's own terminal instead.", target: '#host-terminal-toggle' },
    cloud: { title: "Connect an existing cloud server", body: "Add an existing Linux server from AWS, Google Cloud, Azure or another provider. Supply its SSH address, user and identity file, then verify the server fingerprint.", hint: "Requires SSH and Python 3. Connect/Disconnect does not power the server on or off. Private links are allowed; Local network and Public access are not.", target: '[data-tour="cloud-environment"]' },
    theme: { title: "Choose your appearance", body: "Switch between the dark theme and the softer light theme here. Your preference is saved for the app and its environment windows.", target: '.dashboard-theme' },
    "environment-types": { title: "Choose what to run", body: "New environment offers lightweight containers, NVIDIA CUDA GPU containers, MicroVMs and full VMs. GPU support depends on compatible hardware and runtime setup; it is not promised on every computer.", hint: "We'll start with an ordinary Linux container—no OS installer is needed.", target: '[data-tour="new-environment"]' },
    "windows-overview": { title: "Inside an environment window", body: "You'll find terminal tabs, Install tools, New window and window/environment switchers. Connected nodes also show Skills. Terminal links can appear as QR cards that you can close.", hint: "That's the overview. Next begins the first-container walkthrough using the actual controls.", target: graph, next: "Next" },
    "create-open": { title: "Create your first container", body: "Click New environment. The guide will stay with you inside the form. No environment is created until you press the form's Create environment button.", target: '[data-tour="new-environment"]', interactive: true },
    "create-type": { title: "Choose Container", body: "Select Container for this walkthrough. It gives you a Linux workspace without installing a full operating system. GPU and VM setup are separate workflows.", target: '[aria-label="Isolation options"]', interactive: true, hint: "Select Container, then press Next." },
    "create-name": { title: "Give it a name", body: "Enter a name you will recognize, such as First container. Use at least two characters and a name that is not already in your graph.", target: '[data-tour="create-name"]', interactive: true },
    "create-image": { title: "Choose its Linux image", body: "Open the searchable OCI image list. Ubuntu or Debian is a good starting point for a coding workspace; Alpine is smaller. Purpose shortcuts select an image, not a finished project.", hint: "For this tutorial, choose a general Linux image rather than a database-only image. Leave the suggested keep-alive startup command.", target: '[data-tour="create-image"]', extra: ['[data-slot="combobox-popup"]'], interactive: true },
    "create-resources": { title: "Allocate CPU, memory and storage", body: "Drag the sliders. Minimum is the floor, Preferred is the target, Maximum is the ceiling. For coding tools, allow around 2 GB of memory if your PC has room. Keep some capacity for your PC.", hint: "Leave standard-container storage unchanged for this walkthrough. Enlarging its shared pool may require stopping other containers.", target: '[aria-label="Resource allocation"]', interactive: true },
    "create-submit": { title: "Create the container", body: "Check your choices, then click Create environment below. The first image or runtime download can take a few minutes. The node will appear when preparation finishes.", hint: "Next waits for the real result. If creation fails, read the form's error, correct the settings and retry. Skip never cancels an operation already started.", target: '[data-tour="create-submit"]', extra: ['[data-create-environment] [role="alert"]'], interactive: true },
    created: { title: "This is your new container", body: "Your container is created and has its own node. Its files survive normal stops and starts. We'll attach Internet access before opening it.", target: node },
    "internet-connect": { title: "Connect it to the Internet", body: "Click Internet access at the bottom, then click the connection point underneath your new node. A line and an Internet label confirm that it is connected.", hint: "This uses your PC's Wi-Fi or wired connection. It does not share PC files or publish any ports. Next unlocks when access is connected.", target: '[data-capability-card="internet"]', extra: [`${node} [data-environment-connection-point]`], interactive: true },
    start: { title: "Start and open it", body: "Click Start on your new node. If it is already running, click Open. Wait for preparation to finish; the guide continues in the container's window.", hint: "Start failures remain visible in the app. Correct the error and retry; don't delete or reset the environment just to continue the guide.", target: `${node} [data-tour="node-launch"]`, extra: ['[role="alert"]'], interactive: true },
    "first-window": { title: "Opening your container…", body: "Keep Yougori open while it starts. The instructions will move into the new container window automatically.", hint: "If you cannot see it, check your taskbar. Skip ends the guide only; it does not stop the container.", target: node },
    terminal: { title: "This terminal is inside the container", body: "Commands here run in the container, not in your PC's PowerShell. Wait until its prompt is ready. Paste works with Ctrl+V; Ctrl+C interrupts a command when no text is selected.", hint: "You control every command. The guide does not type or run anything for you.", target: '[data-tour="guest-terminal"]' },
    tabs: { title: "Separate terminals, same container", body: "Each tab is a separate terminal session. Use + for another tab; files remain shared because the tabs belong to the same container. Closing a tab ends that terminal session.", target: '[data-workspace-tabs]' },
    install: { title: "Install Codex", body: "Open Install tools, then choose Codex. Its installer starts in a fresh terminal tab so it does not overwrite what you were typing. Internet access must stay connected.", hint: "Click the real Codex menu item. The guide advances only after the installer command is sent. If it fails, check the terminal error and retry from Install tools.", target: '[data-tour="install-tools"]', extra: ['[data-tour="installer-menu"]'], interactive: true },
    "install-running": { title: "Watch the installation", body: "The Codex installer has been started—not yet verified as finished. Read this tab's output and wait for its completion message. If it reports an error, fix that error before continuing.", hint: "Next does not mean installation succeeded. Keep this tab open until the installer finishes.", target: '[data-tour="guest-terminal"]', interactive: true },
    "new-terminal": { title: "Open a fresh terminal tab", body: "When installation has finished, click + beside the tabs. A fresh terminal picks up the newly installed tool's environment.", target: '[data-tour="new-terminal"]', interactive: true },
    "run-codex": { title: "Use Codex in the container", body: "Type codex and press Enter in this terminal. Follow the tool's own account and setup prompts. If it says command not found, return to the installer output and check whether installation finished.", hint: "The guide does not sign in, enter credentials, or submit prompts. Press Next when you're ready to learn about windows.", target: '[data-tour="guest-terminal"]', interactive: true },
    "new-window": { title: "Open another window", body: "Click New window. It opens this same running container in a separate window with its own terminal tabs. It does not create or copy another container.", hint: "Your files are shared between these windows. The guide will continue in the new one.", target: '[data-tour="new-window"]', interactive: true },
    "second-window": { title: "Opening another window…", body: "The next tip will appear in the newly opened window. Both windows use the same container and files.", target: '[data-tour="new-window"]' },
    "window-switcher": { title: "Move between open windows", body: "Windows lists the environment windows that are already open. Select one to bring it to the front. Closing a window is different from stopping the container.", target: '[data-tour="window-switcher"]' },
    "environment-switcher": { title: "Switch environments", body: "The name menu switches this window to another environment. Each environment keeps its own files and permissions; switching the view does not connect their files automatically.", target: '[data-tour="environment-switcher"]' },
    "demo-start": { title: "Run your Hello World website", body: "In this new window's empty terminal, paste the command below and press Enter. It installs Python 3 if needed and runs a small website on port 3000. Wait for “Hello World ready”, then click Check website.", hint: "Internet must stay connected for installation. Only a fixed page is served—no folders or PC files. Keep this terminal open; Ctrl+C stops the website. Check website only checks it, it does not publish it.", target: '[data-tour="guest-terminal"]', interactive: true },
    "demo-return": { title: "Your website is running", body: "Yougori checked the Hello World response inside your container. Keep this website terminal running. Continue below, then switch to the main Yougori window from your taskbar to add and publish the port.", hint: "If you close this terminal or stop the container, the website stops too.", target: '[data-tour="guest-terminal"]', next: "Continue on main window" },
    "demo-port-open": { title: "Add the website's port", body: "On your tutorial container, click PORT. We'll add 3000—the same port used by the Hello World website. Even if it was detected automatically, adding the same port does not create a duplicate.", target: `${node} [data-tour="node-port"]`, interactive: true },
    "demo-port-add": { title: "Enter port 3000", body: "Enter 3000 in Guest TCP port, or click the 3000 shortcut, then click Add port. The connection options will open next. This step alone does not publish your website.", target: `[data-add-service-port="${tour.environmentId ?? ""}"]`, interactive: true },
    "demo-publish": { title: "Get a free public link", body: "Choose Public access / Cloudflare Tunnel, keep Quick link — no account selected, then press Publish service. This makes the Hello World page accessible on the public Internet.", hint: "No login, payment or domain purchase is needed. Cloudflare assigns a temporary random trycloudflare.com address—not a permanent domain you own. Wait for the link; the first helper download may take a while. Skip does not cancel publishing already started.", target: serviceDialog, interactive: true },
    "demo-link": { title: "Open your public website", body: "Your public link is ready. Click the HTTPS address in these connection options to open it in your browser. You can also copy it and visit it from a phone or another computer.", hint: "A connected tunnel is not proof the page loaded. If you see an error, keep the website terminal running and wait briefly, then retry the link. Disconnect Cloudflare here to take the site offline.", target: serviceDialog, interactive: true },
    "demo-visit": { title: "Does it say Hello World?", body: "Check the browser tab you opened. If you see Hello World, your container website is now reachable through its public link. Return here and press Next when you have confirmed it.", hint: "To take it offline, use Disconnect cloudflare here. The link also stops when Yougori or the container stops, and a new tunnel gets a new address. Closing the browser is not the same as disconnecting.", target: serviceDialog, interactive: true },
    done: { title: "You're ready to explore", body: "You've created a container, connected Internet access, learned about tools and windows, and published your first Hello World website.", hint: "Finish keeps your environment and any active public link. Disconnect Cloudflare in the port's options when you no longer want it public. Use Instructions to replay the guide.", target: node, extra: [serviceDialog], interactive: true, next: "Finish" },
  }
  return content[step]
}
